---
 - name: This is a simple playbook to understand command line arguments
   hosts: desktops
   gather_facts: false
   #become: yes
   tasks:
   - name: working with {{pkg}}
     apt:
      name: "{{pkg}}"
      state: "{{req_state}}"
   
